services:
  backend:
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      VPN_API_MOCK: "true"
    ports:
      - "9229:9229"

  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  prometheus:
    ports:
      - "9090:9090"

  grafana:
    ports:
      - "3001:3000"
